language: generic

env:
  global:
  - secure: pkvNpm2ODc7INi5L8RqyqdVK73nN+WkQuTIzL52L+dcQIVaLqWupAK1zuBq6NeqQEgQcTvRFP5oCbsYLPYY5sBKpU/1WhS+UL9l9bmhYvYIgv1fyH7eH3PLuKEIGTaAVoMHFLStA+WHIuyK5UsmcZouVKn6vLQDK+XeZiyNxU3T2bONyabRDmc5JgdAjh4vdjrRupqq3CfZjaVCOnD+NBAYIHPZZnQc+9Dt6W9n9fjEO0B+2zi7NZEEP3dgeGsmws9M2wzbPJciWkFAOLBg66mPrSl7Vcl8KwVqWI9Wcb2/ogKU+CB0et4vwOdltBMdy29IRb0fxHrpP+sucHu32r9rWCAxdAXOdOgh5neYs/f8QSvk1BLaL1bNmMXe+APajFvukdxLUuYczX38rBjtXdrjrJRZ0Eyj8YK0g3r2HupbJ9FWM+adQKRYN2KV5yaqK6rpWa1/5XiNnfZYbQTbpdWSukNn48jTACDvhNwEDP9XeJ+CR7EOv4lc69wG+XHnv4Mr94TQvq9i4OKXCgh1kI7OGVNrcAyTX8sGDYlK4oc8TD0/aq7bzzGQmyBRQdEp2bKjVQo7lDE6g8baj+F1iw+8cfAJ1DjS/0brHTQpsTStBnWQWxEHOWtUitOKGoNkRxUaWgiAEq/npUr/UrrENPUuHsP1V48NXsG0vYLmr9mw=
  - secure: KBR7yxM33eyTSAFEUpP55oS9fq2MzcM3hlPaXpYQXOOZUFMjpSbmeBnDA3CozPS8oMCPqL6cS/cOxPXb4/XhWvQLcib8LIh5+iX9wmqWcJkpXXaZGPqe8mZ5x57GlspFTMSV3VzSzE2cLbCzuaGhmMCgwuue0BJPPEAaKLmiPfdA/gS2O6VvsLssTP+QqHybd3oqZE6DFVU9FW9O0g1q8QPS0tiaft0BeMMvzOLONgBU0shEuQ9S+gdUH/8qpyD4Uh+t3SzcRSTG5mGIG9Ke2DPTo8LUfveEg3o5wOfj3hvEionOPdBFV96M7JwV0a5g6xEPk1NbV6s6BwPgSN2fwoVSdwzhD2kPVMFqEBX8TliQFVrrbpK1z8y+4nTdjLfPLf+KtHfE2Twj9bxb1TyO26M1l8Vq9lqIMfqHzgI04S75IiLLmmRXOQRCKAFb1xsqn2kIkwnctGDb8AHvMdk10qrD2Ww6qls0WAp3IWvMZED+i1M3nGQeO2x5vDQQNWIZsx/QR/nGl7dW68mF8LwyTuE0hJyGG+SjH3IHUTPQKqkhy85npYQpNihUPtQGqIL6LSBh5GYC5SjEH93FLkCoxRo9z5e4MOMy1KBZT+y4H5XvAxKYDz44/FZVzEYhRSZ3OJsn0FogsuJv+bvQlSxXBEt1x9yzn7Pl62Sm7yrr05o=

jobs:
  include:
  - os: linux
    python: 2.7
    env: TRAVIS_PYTHON_VERSION=2.7
  - os: osx
    python: 2.7
    env: TRAVIS_PYTHON_VERSION=2.7

before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  else
    # Install Miniconda
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  fi
  bash miniconda.sh -b -p $HOME/miniconda
  export PATH="$HOME/miniconda/bin:$PATH"
  conda install -y conda-build
  conda config --add channels conda-forge

script:
 - |2
    if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
      # Workaround to avoid build timeout
      while sleep 500; do
        echo "====[ $SECONDS seconds still running ]===="
      done &
      # A cron build. We install 3ML as a user would do by using the install_3ML script
      chmod u+x ci/cron_install_and_test.sh
      ./ci/cron_install_and_test.sh
    else
      chmod u+x ci/build_and_test.sh
      ./ci/build_and_test.sh
    fi

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: KlyYSpxgxR5LKd+xouGwady5yuKDlpeucB7P0FMBQduq2hd50jKJ+HPOungkN5R2htKzTrNy+cYSioNr/6RxXG6z4fBkG+rQvjUyX33az3k6Af/yDFUVtu1uYaWai+S04NIk1814JYH6rCmLpQeEvK6DPiiK67w1lV3hXqaGqS6CTFj7oB4KcpWtD35rPfu9iC4w1AUxSzO0VumdP3RwCH5zVmtf5QaoxzBJkqCV4duqIUdlEe1I/mg3yxkICFMZW9lZmkSb5lKSRMrNWsBZ7Gy25seBe3LMQSdpUwINMubSLmJgDccx9tMlld3+fOhpQx53aeU11xHYPHvKvNl5y+cxMGae2tdbcibvKKbHDrhgxacBag//SoVAoWYBLQnkeuUsCMMIaNUS0FnTlpXF/sAVTvyHhBeo+CIJ0TPp0BuqVyb7AObvdXRf2wRwIPBK553zJrqyPpDd3SzpkX4AX+tsoQCJzp/1DUZvNGZSXWMcJB/QICMWiOXk2uIzmtBoNWrpdC5ERGhUVwBy4aXboGMn9oI01utQO82u79GIv5FfWKNCy3AqrMazcRBpTVNs0y0y9JsQYTonkAiS60h0afpQEgSwf74h0acNReb6G1Ndmhe+vY80IgN30V1kIxT1wmGYIeFKKPthHIpG4WGTYwU5vGh/iG0769Bipl4um84=
  distributions: sdist
  skip_existing: true
  on:
    tags: true
  
