{% set name = "speclite" %}
{% set version = "0.7" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  fn: '{{ name }}-{{ version }}.tar.gz'

build:
  number: 0

requirements:

  build:
    - python x.x
    - setuptools
    - astropy-helpers
    - numpy
    - matplotlib

  run:
    - python x.x
    - numpy
    - matplotlib
    - astropy
    - scipy

test:
  imports:
    - speclite

about:
  license: BSD License
  license_family: BSD
  summary: 'This package provides a set of lightweight utilities for working with spectroscopic data in astronomy. Based on the astropy affiliated package template.'

extra:
  recipe-maintainers:
    - giacomov
