package:
  name: threeml
  version: "0.4.0"

source:
  git_url: https://github.com/giacomov/3ML.git

requirements:
  
  build:
    - python x.x
    - toolchain
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml
    - dill
    - iminuit >=1.2
    - astromodels >=0.4
    - corner >=1.0.2
    - pandas
    - requests
    - speclite
    - pymultinest
    - cthreeml
    - ipywidgets
    - ipython
    - ipyparallel
    - py

  run:
    - python x.x
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml
    - dill
    - iminuit >=1.2
    - astromodels >=0.4
    - corner >=1.0.2
    - pandas
    - requests
    - speclite
    - pymultinest
    - cthreeml
    - ipywidgets
    - ipython
    - ipyparallel
    - xz
    - py

test:
  # Python imports
  commands:
    - python -c 'import os;os.environ["MPLBACKEND"]="Agg";from threeML import *'


about:
  home: https://github.com/giacomov/3ML
  license: BSD-3
  summary: 'The Multi-Mission Maximum Likelihood framework'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov

