package:
   name: heasoft-xspec
   version: "6.22.1"

source:
  fn: heasoft-6.22.1src.tar.gz
  url: http://fermigrb.stanford.edu/heasoft-6.22.1src.tar.gz

build:
  number: 0

requirements:
  
 build:
     - python x.x
     - toolchain
     - perl >=5.22
     - autoconf
     - automake
     - cfitsio
     - readline
     - openssl
     - gcc
     - libgfortran
     - xorg-libx11
     - xorg-libxt
     - xorg-libxcursor
     - tk >=8.6

 run:
     - python x.x
     - perl >=5.22
     - cfitsio
     - readline
     - openssl
     - libgfortran
     - xorg-libx11
     - xorg-libxt
     - xorg-libxcursor
     - tk >=8.6

extra:
  maintainers:
   - giacomov

test:
  commands:
    - test -f ${PREFIX}/lib/libape_2.9.so [linux]
    - test -f ${PREFIX}/lib/libhdinit_2.7.so [linux]
    - test -f ${PREFIX}/lib/libhdio_2.7.so [linux]
    - test -f ${PREFIX}/lib/libhdutils_2.7.so [linux]
    - test -f ${PREFIX}/lib/libhoops_1.1.so [linux]
    
    - test -f ${PREFIX}/lib/libape_2.9.dylib [osx]
    - test -f ${PREFIX}/lib/libhdinit_2.7.dylib [osx]
    - test -f ${PREFIX}/lib/libhdio_2.7.dylib [osx]
    - test -f ${PREFIX}/lib/libhdutils_2.7.dylib [osx]
    - test -f ${PREFIX}/lib/libhoops_1.1.dylib [osx]
    
    - test -d ${PREFIX}/include/ape
    - test -d ${PREFIX}/include/hoops
    - test -f ${PREFIX}/include/headas.h
    - test -f ${PREFIX}/include/pil.h
    
    - conda inspect linkages --show-files -p $PREFIX heacore  # [not win]
    - conda inspect objects -p $PREFIX heacore  # [osx]


about:
  home: https://heasarc.gsfc.nasa.gov/lheasoft/
