name: Python Package using Conda

on:
  push:
  #schedule:
  #  - cron: "0 20 * * *"
  
jobs:
  test-threeml:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install threeML
      run: |
        bash install_3ML.sh --batch --python 3.7
    - name: test threeML
      run: |
        source threeML_init.sh
        pytest -vv --pyargs threeML
        pytest -vv --pyargs astromodels
      env:
        OMP_NUM_THREADS: 1
        MKL_NUM_THREADS: 1
        NUMEXPR_NUM_THREADS: 1
        MPLBACKEND: "Agg"


